### ISSUE TITLE
[MINI-EPIC] View 2: TV Shows

### ISSUE THREAD

**Issue by kryanbeane** [kryanbeane/cinematix#17]
**Describe the solution you'd like**
A new view with accompanying routes, endpoints and as-needed storybook support for new components for showing TV Shows and information on them. This will include a parameterized URL for individual tv show pages.

**Additional context**

**Tasks**
- [ ] Show view components
- [ ] Storybook
- [ ] Show API calls
- [ ] Shows page
- [ ] Tv Show details page
- [ ] Menu button for Shows
